export { searchGames, searchGamesByIds, getPopularGames } from './games'
export { getRecommendations } from './recommendations'
export { getGenres } from './genres'
export { generateAccount, regenerateToken, getMe, deleteAccount, logout, loginByToken } from './auth'
export { importSteamLibrary, scanSteamLibrary } from './steam'
export { activatePromoCode } from './subscription'
export { sendFeedback } from './feedback'
export { getPlatforms } from './platforms'
